-   id: rdf-toolkit-normalizer
    name: RDF Toolkit Normalizer
    description: confirms TTL files are normalized.
    entry: rdf-toolkit-normalizer
    language: python
    types: [file] 
    files: \.ttl$
