# action.yml
name: 'RDF Toolkit Normalizer'
description: 'Normalizes RDF files utilizing rdf-toolkit.jar'
inputs:
  input-file:
    description: 'The path to the file to be normalized'
    required: true
    default: 'input.ttl'
outputs:
  output-file:
    description: 'The filename for the resulting normalized file. If the provided input is not a valid graph, this file will be empty'
runs:
  using: 'docker'
  image: 'docker://kchason/rdf-toolkit-normalizer:latest'
  env:
    INPUT_TTL_FILE: ${{ inputs.input-file }}
