name: Build Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tag Name
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: kchason/rdf-toolkit-normalizer

      - name: Build and Push Latest
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kchason/rdf-toolkit-normalizer:latest

      - name: Build and Push Tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
