on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous Integration
jobs:
  build:
    strategy:
      matrix:
        java-version: [11, 18]
        python-version: [3.8, "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-commit Checks
      run: |
        pip -q install pre-commit
        pre-commit run --all-files
