name: Repository Checks

on: [ push ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      # Get the code from the repository to be packaged
      - name: Get Repo
        uses: actions/checkout@v2

      - name: Run Action - Specific File
        uses: ./
        with:
          input-file: "/src/test_files/investigation.ttl"
      